server:
  port: 8080
  
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basmaonlinestore
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect 
      
    